name: Fatboys
favicon: null
layout_spectrum: 0.74819
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040d14'
    - '#372c30'
    - '#856b4b'
    - '#b58a9f'
    - '#dfd7ad'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
